### ISSUE TITLE
Error creating bean with name 'apmClient' defined in class path resource

### ISSUE THREAD

**Issue by jvaldenor** [michaelhyatt/elastic-apm-mule3-agent#1]
Specs:

- Mule EE runtime version 3.9.1

Deployement failed due to issue `Error creating bean with name 'apmClient' defined in class path resource`

StackTrace:

`Caused by: org.mule.api.lifecycle.InitialisationException: Error creating bean with name 'apmClient' defined in class path resource [co/elastic/apm/mule/tracer.xml]: Invocation of init method failed; nested exception is java.lang.IllegalAccessError: tried to access field co.elastic.apm.agent.shaded.bytebuddy.dynamic.Nexus.NO_QUEUE from class co.elastic.apm.agent.shaded.bytebuddy.dynamic.NexusAccessor
	at org.mule.registry.AbstractRegistry.initialise(AbstractRegistry.java:112) ~[mule-core-3.9.1.jar:3.9.1]
	at org.mule.config.spring.SpringXmlConfigurationBuilder.createSpringRegistry(SpringXmlConfigurationBuilder.java:177) ~[mule-module-spring-config-3.9.1.jar:3.9.1]
	at org.mule.config.spring.SpringXmlConfigurationBuilder.doConfigure(SpringXmlConfigurationBuilder.java:100) ~[mule-module-spring-config-3.9.1.jar:3.9.1]
	at org.mule.config.builders.AbstractConfigurationBuilder.configure(AbstractConfigurationBuilder.java:43) ~[mule-core-3.9.1.jar:3.9.1]
	at org.mule.config.builders.AbstractResourceConfigurationBuilder.configure(AbstractResourceConfigurationBuilder.java:69) ~[mule-core-3.9.1.jar:3.9.1]
	at org.mule.config.builders.AutoConfigurationBuilder.autoConfigure(AutoConfigurationBuilder.java:102) ~[mule-core-3.9.1.jar:3.9.1]
	at org.mule.config.builders.AutoConfigurationBuilder.doConfigure(AutoConfigurationBuilder.java:54) ~[mule-core-3.9.1.jar:3.9.1]
	at org.mule.config.builders.AbstractConfigurationBuilder.configure(AbstractConfigurationBuilder.java:43) ~[mule-core-3.9.1.jar:3.9.1]
	at org.mule.config.builders.AbstractResourceConfigurationBuilder.configure(AbstractResourceConfigurationBuilder.java:69) ~[mule-core-3.9.1.jar:3.9.1]
	at org.mule.context.DefaultMuleContextFactory$1.configure(DefaultMuleContextFactory.java:89) ~[mule-core-3.9.1.jar:3.9.1]
	at org.mule.context.DefaultMuleContextFactory.doCreateMuleContext(DefaultMuleContextFactory.java:222) ~[mule-core-3.9.1.jar:3.9.1]
	at org.mule.context.DefaultMuleContextFactory.createMuleContext(DefaultMuleContextFactory.java:81) ~[mule-core-3.9.1.jar:3.9.1]
	at org.mule.module.launcher.application.DefaultMuleApplication.init(DefaultMuleApplication.java:210) ~[mule-module-launcher-3.9.1.jar:3.9.1]
	... 61 more`

**Comment by michaelhyatt** [comment]
I fixed it in the master by declaring a couple of beans as singletons and tested it with an application based on 2 Mule projects deployed into a domain, which seems to fix the issue. Projects deployed into a domain have to be instrumented with tracer.xml each. Check out example-domain-app that I added. Do a git pull to get the latest changes.
