### ISSUE TITLE
Error:java.lang.NoClassDefFoundError: co/elastic/apm/api/Span

### ISSUE THREAD

**Issue by MuleElk** [michaelhyatt/elastic-apm-mule3-agent#36]
+ Failed to deploy artifact 'sample-app', co/elastic/apm/api/Span              +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ERROR 2020-09-01 09:25:22,352 [WrapperListener_start_runner] org.mule.runtime.module.deployment.internal.DefaultArchiveDeployer: Failed to deploy artifact [sample-app]
org.mule.runtime.deployment.model.api.DeploymentException: Failed to deploy artifact [sample-app]
Caused by: java.lang.NoClassDefFoundError: co/elastic/apm/api/Span
       at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_232]
       at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_232]
       at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[?:1.8.0_232]
       at net.sf.cglib.core.ReflectUtils.addAllMethods(ReflectUtils.java:416) ~[cglib-nodep-3.2.10.jar:?]
       at net.sf.cglib.proxy.Enhancer.getMethods(Enhancer.java:540) ~[cglib-nodep-3.2.10.jar:?]
       at net.sf.cglib.proxy.Enhancer.getMethods(Enhancer.java:535) ~[cglib-nodep-3.2.10.jar:?]
       at net.sf.cglib.proxy.CallbackHelper.<init>(CallbackHelper.java:34) ~[cglib-nodep-3.2.10.jar:?]
       at org.mule.runtime.core.privileged.component.AnnotatedObjectInvocationHandler$1.<init>(AnnotatedObjectInvocationHandler.java:96) ~[mule-core-4.3.0.jar:4.3.0]
       at org.mule.runtime.core.privileged.component.AnnotatedObjectInvocationHandler.addAnnotationsToClass(AnnotatedObjectInvocationHandler.java:96) ~[mule-core-4.3.0.jar:4.3.0]
       at org.mule.runtime.config.internal.dsl.spring.ObjectBeanDefinitionCreator.handleRequest(ObjectBeanDefinitionCreator.java:67) ~[mule-module-spring-config-4.3.0.jar:4.3.0]
       at org.mule.runtime.config.internal.dsl.spring.BeanDefinitionCreator.processRequest(BeanDefinitionCreator.java:41) ~[mule-module-spring-config-4.3.0.jar:4.3.0]
       at org.mule.runtime.config.internal.dsl.spring.BeanDefinitionCreator.processRequest(BeanDefinitionCreator.java:45) ~[mule-module-spring-config-4.3.0.jar:4.3.0]
       at org.mule.runtime.config.internal.dsl.spring.BeanDefinitionFactory.resolveComponentBeanDefinition(BeanDefinitionFactory.java:340) ~[mule-module-spring-config-4.3.0.jar:4.3.0]
       at org.mule.runtime.config.internal.dsl.spring.BeanDefinitionFactory.resolveComponent(BeanDefinitionFactory.java:189) ~[mule-module-spring-config-4.3.0.jar:4.3.0]
       at org.mule.runtime.config.internal.dsl.spring.BeanDefinitionFactory.resolveComponentRecursively(BeanDefinitionFactory.java:178) ~[mule-module-spring-config-4.3.0.jar:4.3.0]
       at org.mule.runtime.config.internal.MuleArtifactContext.lambda$createApplicationComponents$17(MuleArtifactContext.java:573) ~[mule-module-spring-config-4.3.0.jar:4.3.0]
       at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_232]
       at org.mule.runtime.config.internal.dsl.model.SpringComponentModel$1.tryAdvance(SpringComponentModel.java:245) ~[mule-module-spring-config-4.3.0.jar:4.3.0]
       at java.util.Spliterator.forEachRemaining(Spliterator.java:326) ~[?:1.8.0_232]
       at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647) ~[?:1.8.0_232]
       at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:272) ~[?:1.8.0_232]
       at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_232]
       at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_232]
       at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_232]
       at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_232]
       at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_232]
       at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_232]
       at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_232]
       at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_232]
       at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_232]
       at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:272) ~[?:1.8.0_232]
       at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_232]
       at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235) ~[?:1.8.0_232]
       at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_232]
       at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_232]
       at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_232]
       at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_232]
       at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_232]
       at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_232]
       at org.mule.runtime.config.internal.MuleArtifactContext.createApplicationComponents(MuleArtifactContext.java:562) ~[mule-module-spring-config-4.3.0.jar:4.3.0]
       at org.mule.runtime.config.internal.MuleArtifactContext.loadBeanDefinitions(MuleArtifactContext.java:435) ~[mule-module-spring-config-4.3.0.jar:4.3.0]
       at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:133) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
       at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:636) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
       at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:521) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
       at org.mule.runtime.config.internal.SpringRegistry.doInitialise(SpringRegistry.java:101) ~[mule-module-spring-config-4.3.0.jar:4.3.0]
       at org.mule.runtime.core.internal.registry.AbstractRegistry.initialise(AbstractRegistry.java:94) ~[mule-core-4.3.0.jar:4.3.0]
       at org.mule.runtime.core.internal.registry.MuleRegistryHelper.fireLifecycle(MuleRegistryHelper.java:111) ~[mule-core-4.3.0.jar:4.3.0]
       at org.mule.runtime.core.internal.lifecycle.MuleContextLifecycleManager$MuleContextLifecycleCallback.onTransition(MuleContextLifecycleManager.java:73) ~[mule-core-4.3.0.jar:4.3.0]
       at org.mule.runtime.core.internal.lifecycle.MuleContextLifecycleManager$MuleContextLifecycleCallback.onTransition(MuleContextLifecycleManager.java:69) ~[mule-core-4.3.0.jar:4.3.0]
       at org.mule.runtime.core.privileged.lifecycle.AbstractLifecycleManager.invokePhase(AbstractLifecycleManager.java:132) ~[mule-core-4.3.0.jar:4.3.0]
       at org.mule.runtime.core.internal.lifecycle.MuleContextLifecycleManager.fireLifecycle(MuleContextLifecycleManager.java:61) ~[mule-core-4.3.0.jar:4.3.0]
       at org.mule.runtime.core.internal.context.DefaultMuleContext.initialise(DefaultMuleContext.java:300) ~[mule-core-4.3.0.jar:4.3.0]
       at org.mule.runtime.core.api.context.DefaultMuleContextFactory.doCreateMuleContext(DefaultMuleContextFactory.java:188) ~[mule-core-4.3.0.jar:4.3.0]
       at org.mule.runtime.core.api.context.DefaultMuleContextFactory.createMuleContext(DefaultMuleContextFactory.java:59) ~[mule-core-4.3.0.jar:4.3.0]
       at org.mule.runtime.module.deployment.impl.internal.artifact.ArtifactContextBuilder.lambda$build$2(ArtifactContextBuilder.java:499) ~[mule-module-deployment-model-impl-4.3.0.jar:4.3.0]
       at org.mule.runtime.core.api.util.ExceptionUtils.tryExpecting(ExceptionUtils.java:224) ~[mule-core-4.3.0.jar:4.3.0]
       at org.mule.runtime.core.api.util.ClassUtils.withContextClassLoader(ClassUtils.java:966) ~[mule-core-4.3.0.jar:4.3.0]
       at org.mule.runtime.core.api.util.ClassUtils.withContextClassLoader(ClassUtils.java:884) ~[mule-core-4.3.0.jar:4.3.0]
       at org.mule.runtime.module.deployment.impl.internal.artifact.ArtifactContextBuilder.build(ArtifactContextBuilder.java:409) ~[mule-module-deployment-model-impl-4.3.0.jar:4.3.0]
       at org.mule.runtime.module.deployment.impl.internal.application.DefaultMuleApplication.doInit(DefaultMuleApplication.java:239) ~[mule-module-deployment-model-impl-4.3.0.jar:4.3.0]
       at org.mule.runtime.module.deployment.impl.internal.application.DefaultMuleApplication.init(DefaultMuleApplication.java:207) ~[mule-module-deployment-model-impl-4.3.0.jar:4.3.0]
       at org.mule.runtime.core.api.util.ExceptionUtils.tryExpecting(ExceptionUtils.java:265) ~[mule-core-4.3.0.jar:4.3.0]
       at org.mule.runtime.core.api.util.ClassUtils.withContextClassLoader(ClassUtils.java:923) ~[mule-core-4.3.0.jar:4.3.0]
       at org.mule.runtime.core.api.util.ClassUtils.withContextClassLoader(ClassUtils.java:861) ~[mule-core-4.3.0.jar:4.3.0]
       at org.mule.runtime.module.deployment.impl.internal.artifact.DeployableArtifactWrapper.executeWithinArtifactClassLoader(DeployableArtifactWrapper.java:140) ~[mule-module-deployment-model-impl-4.3.0.jar:4.3.0]
       at org.mule.runtime.module.deployment.impl.internal.artifact.DeployableArtifactWrapper.init(DeployableArtifactWrapper.java:83) ~[mule-module-deployment-model-impl-4.3.0.jar:4.3.0]
       at org.mule.runtime.module.deployment.internal.DefaultArtifactDeployer.doInit(DefaultArtifactDeployer.java:65) ~[mule-module-deployment-4.3.0.jar:4.3.0]
       at org.mule.runtime.module.deployment.internal.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:28) ~[mule-module-deployment-4.3.0.jar:4.3.0]
       at org.mule.runtime.module.deployment.internal.DefaultArchiveDeployer.deployArtifact(DefaultArchiveDeployer.java:451) [mule-module-deployment-4.3.0.jar:4.3.0]
       at org.mule.runtime.module.deployment.internal.DefaultArchiveDeployer.internalDeployPackagedArtifact(DefaultArchiveDeployer.java:541) [mule-module-deployment-4.3.0.jar:4.3.0]
       at org.mule.runtime.module.deployment.internal.DefaultArchiveDeployer.deployOrRedeployPackagedArtifact(DefaultArchiveDeployer.java:506) [mule-module-deployment-4.3.0.jar:4.3.0]
       at org.mule.runtime.module.deployment.internal.DefaultArchiveDeployer.deployPackagedArtifact(DefaultArchiveDeployer.java:380) [mule-module-deployment-4.3.0.jar:4.3.0]
       at org.mule.runtime.module.deployment.internal.DefaultArchiveDeployer.deployPackagedArtifact(DefaultArchiveDeployer.java:55) [mule-module-deployment-4.3.0.jar:4.3.0]
       at org.mule.runtime.module.deployment.internal.DeploymentDirectoryWatcher.deployPackedApps(DeploymentDirectoryWatcher.java:241) [mule-module-deployment-4.3.0.jar:4.3.0]
       at org.mule.runtime.module.deployment.internal.DeploymentDirectoryWatcher.run(DeploymentDirectoryWatcher.java:312) [mule-module-deployment-4.3.0.jar:4.3.0]
       at org.mule.runtime.module.deployment.internal.DeploymentDirectoryWatcher.start(DeploymentDirectoryWatcher.java:153) [mule-module-deployment-4.3.0.jar:4.3.0]

**Comment by michaelhyatt** [comment]
Are you trying to use the agent with Mule 4?

**Comment by MuleElk** [comment]
Yes, I am trying on Mule 4.
Is it compatible?

Regards,
Manasa

**Comment by michaelhyatt** [comment]
This is the agent for Mule 3, the one for Mule 4 is here:
https://github.com/michaelhyatt/elastic-apm-mule4-agent

**Comment by MuleElk** [comment]
Hi Michael,
I have installed Mule4 agent from the releases page link:
https://github.com/michaelhyatt/elastic-apm-mule4-agent/releases

I followed the same link you shared and set up the agent.
Still getting the same error message.

I installedmule4-agent-0.0.4.jar
<https://github.com/michaelhyatt/elastic-apm-mule4-agent/releases/download/v0.0.4/mule4-agent-0.0.4.jar>.
Please let me know is this the right Agent jar file?

Regards,
Manasa

**Comment by michaelhyatt** [comment]
did you change your pom file to add a new dependency instead of the other
mule 3 agent?

**Comment by MuleElk** [comment]
Yes, I added and installed the new agent.
Also updated the Pom xml to to reflect these changes and ran the application.

It is looking for that specific class and get the noclassfound error.

Is the jar link I shared the right agent jar?
Is there any other dependencies or jar file to be installed?

Regards,
Manasa

**Comment by michaelhyatt** [comment]
Check out Mule 4 agent repo for instructions, this is the wrong repo. There
are three things you need to do, install the jar, add maven dependency and
reference the tracer.xml in the flow file.

https://github.com/michaelhyatt/elastic-apm-mule4-agent
