### ISSUE TITLE
elasticsearch-apm-mule didn't run

### ISSUE THREAD

**Issue by reynold-lariza** [michaelhyatt/elastic-apm-mule3-agent#5]
Hi @michaelhyatt ,

via `example-app$ docker-compose up`
Please see below logs

```
kibana-apm-mule  | {"type":"log","@timestamp":"2019-02-20T08:34:01Z","tags":["warning","stats-collection"],"pid":1,"message":"Unable to fetch data from reporting collector"}
kibana-apm-mule  | {"type":"log","@timestamp":"2019-02-20T08:34:01Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana-apm-mule  | {"type":"log","@timestamp":"2019-02-20T08:34:01Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana-apm-mule  | {"type":"log","@timestamp":"2019-02-20T08:34:02Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana-apm-mule  | {"type":"log","@timestamp":"2019-02-20T08:34:02Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana-apm-mule  | {"type":"log","@timestamp":"2019-02-20T08:34:02Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana-apm-mule  | {"type":"log","@timestamp":"2019-02-20T08:34:02Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana-apm-mule  | {"type":"log","@timestamp":"2019-02-20T08:34:02Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana-apm-mule  | {"type":"log","@timestamp":"2019-02-20T08:34:02Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana-apm-mule  | {"type":"log","@timestamp":"2019-02-20T08:34:02Z","tags":["warning","elasticsearch","data"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana-apm-mule  | {"type":"log","@timestamp":"2019-02-20T08:34:02Z","tags":["warning","elasticsearch","data"],"pid":1,"message":"No living connections"}
```

docker ps shows

```
$ docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                                                                      NAMES
4bf9c517bb70        example-app_component1                   "sh wait-for-apm-ser…"   4 minutes ago       Up 4 minutes        1099/tcp, 5000/tcp, 7777/tcp, 8899/tcp, 0.0.0.0:8281->8281/tcp             example-app_component1_1
9ae4495a0a2f        example-app_component2                   "sh wait-for-apm-ser…"   4 minutes ago       Up 4 minutes        1099/tcp, 5000/tcp, 7777/tcp, 8899/tcp, 0.0.0.0:8282-8285->8282-8285/tcp   example-app_component2_1
951bf88a7455        docker.elastic.co/apm/apm-server:6.6.0   "/usr/local/bin/dock…"   4 minutes ago       Up 4 minutes        0.0.0.0:8200->8200/tcp                                                     apm-server-apm-mule
d34993f58a3f        docker.elastic.co/kibana/kibana:6.6.0    "/usr/local/bin/kiba…"   4 minutes ago       Up 4 minutes        0.0.0.0:5601->5601/tcp                                                     kibana-apm-mule
```

**Comment by reynold-lariza** [comment]
second time around, but this time with `TAG=6.6.0 docker-compose up`
```
4bf9c517bb70        example-app_component1                                "sh wait-for-apm-ser…"   13 minutes ago      Up 32 seconds       1099/tcp, 5000/tcp, 7777/tcp, 8899/tcp, 0.0.0.0:8281->8281/tcp             example-app_component1_1
9ae4495a0a2f        example-app_component2                                "sh wait-for-apm-ser…"   13 minutes ago      Up 33 seconds       1099/tcp, 5000/tcp, 7777/tcp, 8899/tcp, 0.0.0.0:8282-8285->8282-8285/tcp   example-app_component2_1
951bf88a7455        docker.elastic.co/apm/apm-server:6.6.0                "/usr/local/bin/dock…"   13 minutes ago      Up 34 seconds       0.0.0.0:8200->8200/tcp                                                     apm-server-apm-mule
d34993f58a3f        docker.elastic.co/kibana/kibana:6.6.0                 "/usr/local/bin/kiba…"   13 minutes ago      Up 35 seconds       0.0.0.0:5601->5601/tcp                                                     kibana-apm-mule
79b3879e9d87        docker.elastic.co/elasticsearch/elasticsearch:6.6.0   "/usr/local/bin/dock…"   13 minutes ago      Up 36 seconds       0.0.0.0:9200->9200/tcp, 9300/tcp                                           elasticsearch-apm-mule
```

**Comment by reynold-lariza** [comment]
But I'm seeing this...
```
ibana-apm-mule  | {"type":"log","@timestamp":"2019-02-20T08:42:47Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana-apm-mule  | {"type":"error","@timestamp":"2019-02-20T08:42:47Z","tags":["warning","stats-collection"],"pid":1,"level":"error","error":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n    at sendReqWithConnection (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:226:15)\n    at next (/usr/share/kibana/node_modules/elasticsearch/src/lib/connection_pool.js:214:7)\n    at process._tickCallback (internal/process/next_tick.js:61:11)"},"message":"No Living connections"}
kibana-apm-mule  | {"type":"log","@timestamp":"2019-02-20T08:42:47Z","tags":["warning","stats-collection"],"pid":1,"message":"Unable to fetch data from canvas collector"}
kibana-apm-mule  | {"type":"error","@timestamp":"2019-02-20T08:42:47Z","tags":["warning","stats-collection"],"pid":1,"level":"error","error":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n    at sendReqWithConnection (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:226:15)\n    at next (/usr/share/kibana/node_modules/elasticsearch/src/lib/connection_pool.js:214:7)\n    at process._tickCallback (internal/process/next_tick.js:61:11)"},"message":"No Living connections"}
kibana-apm-mule  | {"type":"log","@timestamp":"2019-02-20T08:42:47Z","tags":["warning","stats-collection"],"pid":1,"message":"Unable to fetch data from kibana collector"}
kibana-apm-mule  | {"type":"error","@timestamp":"2019-02-20T08:42:47Z","tags":["warning","stats-collection"],"pid":1,"level":"error","error":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n    at sendReqWithConnection (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:226:15)\n    at next (/usr/share/kibana/node_modules/elasticsearch/src/lib/connection_pool.js:214:7)\n    at process._tickCallback (internal/process/next_tick.js:61:11)"},"message":"No Living connections"}
kibana-apm-mule  | {"type":"log","@timestamp":"2019-02-20T08:42:47Z","tags":["warning","stats-collection"],"pid":1,"message":"Unable to fetch data from kql collector"}
kibana-apm-mule  | {"type":"error","@timestamp":"2019-02-20T08:42:47Z","tags":["warning","stats-collection"],"pid":1,"level":"error","error":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n    at sendReqWithConnection (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:226:15)\n    at next (/usr/share/kibana/node_modules/elasticsearch/src/lib/connection_pool.js:214:7)\n    at process._tickCallback (internal/process/next_tick.js:61:11)"},"message":"No Living connections"}
kibana-apm-mule  | {"type":"log","@timestamp":"2019-02-20T08:42:47Z","tags":["warning","stats-collection"],"pid":1,"message":"Unable to fetch data from rollups collector"}
kibana-apm-mule  | {"type":"error","@timestamp":"2019-02-20T08:42:47Z","tags":["warning","stats-collection"],"pid":1,"level":"error","error":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n    at sendReqWithConnection (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:226:15)\n    at next (/usr/share/kibana/node_modules/elasticsearch/src/lib/connection_pool.js:214:7)\n    at process._tickCallback (internal/process/next_tick.js:61:11)"},"message":"No Living connections"}
kibana-apm-mule  | {"type":"log","@timestamp":"2019-02-20T08:42:47Z","tags":["warning","stats-collection"],"pid":1,"message":"Unable to fetch data from reporting collector"}
kibana-apm-mule  | {"type":"error","@timestamp":"2019-02-20T08:42:47Z","tags":["warning","stats-collection"],"pid":1,"level":"error","error":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n    at sendReqWithConnection (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:226:15)\n    at next (/usr/share/kibana/node_modules/elasticsearch/src/lib/connection_pool.js:214:7)\n    at process._tickCallback (internal/process/next_tick.js:61:11)"},"message":"No Living connections"}
kibana-apm-mule  | {"type":"log","@timestamp":"2019-02-20T08:42:47Z","tags":["warning","stats-collection"],"pid":1,"message":"Unable to fetch data from kibana_settings collector"}
kibana-apm-mule  | {"type":"log","@timestamp":"2019-02-20T08:42:48Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana-apm-mule  | {"type":"log","@timestamp":"2019-02-20T08:42:48Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana-apm-mule  | Unhandled rejection Error: No Living connections
kibana-apm-mule  |     at sendReqWithConnection (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:226:15)
kibana-apm-mule  |     at next (/usr/share/kibana/node_modules/elasticsearch/src/lib/connection_pool.js:214:7)
kibana-apm-mule  |     at process._tickCallback (internal/process/next_tick.js:61:11)
kibana-apm-mule  | {"type":"log","@timestamp":"2019-02-20T08:42:48Z","tags":["error","elasticsearch","data"],"pid":1,"message":"Request e
```

**Comment by reynold-lariza** [comment]
looks like increasing the memory allocated to Docker on mac from 2GB to 8GB works

**Comment by michaelhyatt** [comment]
I will add it to the instructions on how to run example-app.
